function generate_topologies()
% GENERATE_TOPOLOGIES  Draw and save link geometry for every scenario.
%
%   >> generate_topologies
%
%   Figures are written to /topology as PNG files.

    clc;
    repo = fileparts(mfilename('fullpath'));
    addpath(fullfile(repo, 'utils'));
    assert_requirements();
    p = default_params();
    col = pls_colors();

    dist = p.link_dist_m;

    scenarios = {
        topology_cfg('Baseline: 6 GHz vs 28 GHz', 'topology_baseline', [ ...
            topology_node('Bob', dist, -30, col.bob), ...
            topology_node('Eve', dist, -40, col.eve)])
        topology_cfg('Colluding eavesdroppers (K=4)', 'topology_colluding_eves', [ ...
            topology_node('Bob #1', dist, -40, col.bob), ...
            topology_node('Bob #2', dist,  10, [0 0.5 0.3]), ...
            topology_node('Eve #1', dist, -70, col.eve), ...
            topology_node('Eve #2', dist,  55, [0.6 0 0.2])])
        topology_cfg('Artificial noise @ 6 GHz', 'topology_artificial_noise', [ ...
            topology_node('Bob cluster', dist,  20, col.bob), ...
            topology_node('Eve cluster', dist, -50, col.eve)])
        topology_cfg('Pilot contamination', 'topology_pilot_contamination', [ ...
            topology_node('Bob', dist, -30, col.bob), ...
            topology_node('Eve', dist,  20, col.eve)])
        topology_cfg('Spatial correlation (abstract)', 'topology_spatial_correlation', [ ...
            topology_node('Bob (K=8)', 10, 30, col.bob), ...
            topology_node('Eve', 12, -60, col.eve)])
        topology_cfg('Fairness / ZF normalization', 'topology_fairness', [ ...
            topology_node('Users K=8', 10,  0, col.bob), ...
            topology_node('Eve', 11, 75, col.eve)])
        topology_cfg('Phase noise (6 vs 28 GHz)', 'topology_phase_noise', [ ...
            topology_node('Bob', dist, -10, col.bob), ...
            topology_node('Eve', dist,  15, col.eve)])
        topology_cfg('Channel hardening (statistical)', 'topology_channel_hardening', [ ...
            topology_node('Bob', 8, 25, col.bob), ...
            topology_node('Eve', 8, -25, col.eve)])
        topology_cfg('Low-resolution DAC', 'topology_low_res_dac', [ ...
            topology_node('Bob', 8, 20, col.bob), ...
            topology_node('Eve', 9, -40, col.eve)])
        topology_cfg('Pilot jamming (training phase)', 'topology_pilot_jamming', [ ...
            topology_node('Bob', 8, 15, col.bob), ...
            topology_node('Jammer', 7, -30, [0.9 0.4 0])])
        topology_cfg('CSI aging (6 GHz)', 'topology_csi_aging', [ ...
            topology_node('Bob', dist,  5, col.bob), ...
            topology_node('Eve', dist, -35, col.eve)])
        topology_cfg('Location error / narrow beam', 'topology_location_error', [ ...
            topology_node('Bob (true)', dist, -10, col.bob), ...
            topology_node('Eve', dist,  15, col.eve)])
        topology_cfg('Moving Bob: fixed beam @ 0 deg', 'topology_moving_bob', [ ...
            topology_node('Bob (nominal)', dist,   0, col.bob), ...
            topology_node('Bob (drift)',   dist, -25, [0.3 0.8 0.3]), ...
            topology_node('Eve', dist, 22, col.eve)], ...
            'beam_angle_deg', 0, 'beam_width_deg', 8)
    };

    fprintf('Generating %d topology figures in /topology ...\n', numel(scenarios));
    for k = 1:numel(scenarios)
        plot_topology(scenarios{k});
    end
    fprintf('Done.\n');
end

% -------------------------------------------------------------------------
function cfg = topology_cfg(title, filename, nodes, varargin)
% TOPOLOGY_CFG  Build a scalar scenario config for plot_topology.
    cfg = struct('title', title, 'filename', filename, 'nodes', nodes, ...
                 'bs_angle_deg', 90);
    for i = 1:2:numel(varargin)
        cfg.(varargin{i}) = varargin{i+1};
    end
end

function n = topology_node(name, dist_m, angle_deg, color)
% TOPOLOGY_NODE  One user / eavesdropper marker on the map.
    if nargin < 4 || isempty(color)
        color = pls_colors().bob;
    end
    n = struct('name', name, 'dist_m', dist_m, 'angle_deg', angle_deg, ...
               'color', color);
end
